steps:
  # Step 1: Pull the cached image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest || exit 0']

  # Step 2: Build the Docker image using the cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '--cache-from', '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest',
      '.',
      '-f', 'Dockerfile'
    ]
    id: Build

  # Step 3: Tag the image as 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest'
    ]
    id: Tag

  # Step 4: Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    ]
    id: Push_SHA

  # Step 5: Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest'
    ]
    id: Push_Latest

  # Step 6: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: [
      'run', 'services', 'update', '$_SERVICE_NAME',
      '--platform=managed',
      '--image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
      '--labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID',
      '--region=$_DEPLOY_REGION',
      '--quiet'
    ]
    id: Deploy
    entrypoint: gcloud

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest'

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
