# Generated by Django 3.2.6 on 2024-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('chat', 'Chat'), ('playground', 'Playground'), ('mentor', 'Mentor')], default='chat', max_length=10, verbose_name='Type'),
        ),
    ]
