# Generated by Django 3.2.6 on 2024-10-14 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='interview_prep/images/', verbose_name='Icon')),
                ('interview_sys_prompt', models.TextField(verbose_name='Interview system prompt')),
                ('eval_sys_prompt', models.TextField(verbose_name='Evaluation system prompt')),
                ('initial_message', models.CharField(max_length=300, verbose_name='Initial message')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(editable=False, max_length=255, verbose_name='User ID')),
                ('user_email', models.CharField(max_length=255, verbose_name='User email')),
                ('ai_grade', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='AI grade')),
                ('ai_feedback', models.CharField(blank=True, max_length=455, verbose_name='AI feedback')),
                ('ai_strength', models.CharField(blank=True, max_length=400, verbose_name='AI strength')),
                ('ai_weakness', models.CharField(blank=True, max_length=400, verbose_name='AI weakness')),
                ('user_grade', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='User grade')),
                ('user_feedback', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview_prep.interviewprep', verbose_name='Interview prep')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_is_user', models.BooleanField(blank=True, default=False, verbose_name='Author is user?')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('user_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interview_prep.userinterviewprep', verbose_name='User interview prep')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
